#MYSQL_PASSWORD={1}
#dnf module disable mysql -y
#cp mysql.repo  /etc/yum.repos.d/mysql.repo
#dnf install mysql-community-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass ${MYSQL_PASSWORD}


- name: Mexpense project setup
  hosts: all
  become: yes
  roles:
     - {{ service_name }}




