#MYSQL_PASSWORD={1}
#dnf module disable mysql -y
#cp mysql.repo  /etc/yum.repos.d/mysql.repo
#dnf install mysql-community-server -y
#systemctl enable mysqld
#systemctl start mysqld
#mysql_secure_installation --set-root-pass ${MYSQL_PASSWORD}


- name: MySQL Setup
  hosts: all
  tasks:
    - name: Disable MySQL Module Default Version
      ansible.builtin.shell: dnf module disable mysql -y            #dnf disable module not there in ansible so go with shell


    - name: Copy Mysql Repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: instatll my sql server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: installed

    - name: start mysql service
      ansible.builtin.systemd_service:
        name: mysqld
        state: restarted

    - name: Set Mysql Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1


