- name: Disable default Version of NodeJS
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable Nodejs version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Configure backend service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application user
  ansible.builtin.user:
    name: expense

- name: Remove exiting App Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: true

- name: Download Dependencies
  community.general.npm:
    path: /app

- name: Reloading SystemD and Start backend Service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes

- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed


- name: Install python Library for MySQL
  ansible.builtin.dnf:
    name: python3-PyMySQL
    state: installed

- name: Load Scheme
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.tejas1996.online